### PR TITLE
colibri-imx8x: board integration for Toradex BSP 5.7.0

### PR DESCRIPTION
**Pull request by mrpelotazo**
Adds mender support for Toradex colibri imx8x board for Toradex BSP 5.7.0

### CODE REVIEW

**Comment by drewmoseley** [comment]
@mrpelotazo thanks for investigating this. I realized we didn't yet have support for BSP 5.7.0 but fortunately, the 5.6.0 files work unmodified. I created https://github.com/mendersoftware/meta-mender-community/pull/281 which adds symlinks for 5.7.0. Can you rebase this on top of that?

**Comment by mrpelotazo** [comment]
Yes. I'm waiting for #281 to be merged.

**Comment by mrpelotazo** [comment]
@drewmoseley how is it going with #281? It seems to be no reaction.

**Comment by drewmoseley** [comment]
From my POV it is ready.  Waiting on @TheYoctoJester. I know he was traveling for ELC so probably just getting back around to these things.

**Review by TheYoctoJester — APPROVED** [review]

**Comment by TheYoctoJester** [comment]
Sorry for the delay, I was indeed traveling and on PTO. The changes look good to me, but can you please rebase respectively fix the conflicts? Then I can merge it. Thanks! @mrpelotazo

**Pull request merged**
