### PR TITLE
toradex: Add support for Toradex BSP 6.2.0

### PR DESCRIPTION
**Pull request by drewmoseley**

### CODE REVIEW

**Comment by drewmoseley** [comment]
@TheYoctoJester ping

**Review by TheYoctoJester — APPROVED** [review]

**Comment by TheYoctoJester** [comment]
@drewmoseley ack

**Comment by mattes-bru** [comment]
When I try to build the tdx-reference-minimal-image for an apalis-imx8 machine with these changes I get an error during the patch state of  u-boot-toradex-2022.04-r0: 

`Patch 0001-configs-toradex-board-specific-mender-integration.patch does not apply`

Am I doing something wrong or is this PR not behaving as expected?

**Comment by drewmoseley** [comment]
@mattes-bru what is the value of your TORADEX_BSP_VERSION variable?

**Comment by mattes-bru** [comment]
the variable is not set. I followed along the QuickStart of the README but used another repo init:

```
repo init -u https://git.toradex.com/toradex-manifest.git \
    -b refs/tags/6.2.0 \
    -m tdxref/default.xml
```

I also needed to alter the mender manifest a little:

```
wget --directory-prefix .repo/local_manifests \
    https://raw.githubusercontent.com/mendersoftware/meta-mender-community/kirkstone/scripts/mender-no-setup-layers.xml
```

**Comment by mattes-bru** [comment]
@drewmoseley: Thank you. Everything works as expected. I added a PR  with an updated version of the README #348

**Pull request merged**
