### PR TITLE
Bump poky revisions to Dunfell (qemu, bbb,rpi,odroid)

### PR DESCRIPTION
**Pull request by oleorhagen**

### CODE REVIEW

**Comment by oleorhagen** [comment]
Pi follow up: https://github.com/mendersoftware/meta-mender-community/pull/174/files

**Comment by mirzak** [comment]
Any plans to follow up on the others? Wondering if I should close this one?

**Comment by oleorhagen** [comment]
> Any plans to follow up on the others? Wondering if I should close this one?

Still on my TODO. At least the bbb. Not sure if we have an odroid available. So if you don't mind I'd like to keep this open a few more weeks :pray: (sry this is taking so long).

**Comment by mirzak** [comment]
Thanks for the update.

> Not sure if we have an odroid available.

It should be in the Oslo office.

**Comment by oleorhagen** [comment]
bbb: https://github.com/mendersoftware/meta-mender-community/pull/186

**Comment by oleorhagen** [comment]
Closing, I'll get to the odroid whenever

**Pull request closed without merging**
