### PR TITLE
initial support for Siemens IOT2000

### PR DESCRIPTION
**Pull request by mirzak**
The default settings assume that one is booting from USB.

The integration actually does not work yet, due to this error:

```
root@iot2000:~# mender                                                                                                                                                                                            
This program can only be run on processors with MMX support.
```

See [this](https://support.industry.siemens.com/tf/WW/en/posts/mmx-in-iot2020/201161?page=0&pageSize=10) for more information on why. Essentalily `golang` does not work in the SoC used by IOT2000 board. They do have a fork of golang with a patchset that resolves this, but they only have patches for 1.6 and 1.8 versions of go (1.8 was used in pyro)

But I would still like to merge this, in the hopes that someone see it and fixes it.

Also as the [meta-iot2000](https://github.com/siemens/meta-iot2000) uses [kas](https://github.com/siemens/kas), I have added support for this in meta-mender-community and added a `kas.yml` for iot2000 board along with a generic one for Mender

### CODE REVIEW

**Comment by mirzak** [comment]
> See this for more information on why. Essentalily golang does not work in the SoC used by IOT2000 board. They do have a fork of golang with a patchset that resolves this, but they only have patches for 1.6 and 1.8 versions of go (1.8 was used in pyro)

This became to big of a hurdle to workaround and not working any more on this.

Closing, might re-open if there is interested from someone

**Comment by mkozjak** [comment]
@mirzak - Thanks for this work so far! I'm interested if there's any thoughts from your side on the current state of the integration with SoC used by IOT2050 board. Any chances if it's possible to tackle integration at all?

**Comment by mirzak** [comment]
> Any chances if it's possible to tackle integration at all?

I have not looked at this in a while, but unless anything has changed in regards to `go` support, it is very steep hill to climb :)

**Comment by mirzak** [comment]
Some references I found back when I worked on this:

https://support.industry.siemens.com/tf/ww/en/posts/golang-1-9-in-iot2020/187790/?page=0&pageSize=10
https://github.com/siemens/meta-iot2000/issues/96

**Comment by mkozjak** [comment]
Thanks, @mirzak!

**Comment by mirzak** [comment]
I realized misread your comment. You asked about IOT2050, I know nothing about this one :)

**Comment by mkozjak** [comment]
@mirzak - no worries - https://github.com/siemens/meta-iot2000/issues/96#issuecomment-694289753

**Pull request closed without merging**
