### PR TITLE
001-Adapt-boot.cmd.in-to-Mender.patch: Fix

### PR DESCRIPTION
**Pull request by leon-anavi**
Fix the patch to affoid the following issues:

Applying patch 0001-Adapt-boot.cmd.in-to-Mender.patch
patching file boot.cmd.in
Hunk #3 FAILED at 41.
1 out of 3 hunks FAILED -- rejects in file boot.cmd.in
Patch 0001-Adapt-boot.cmd.in-to-Mender.patch does not apply (enforce with -f)

Signed-off-by: Leon Anavi <leon.anavi@konsulko.com>

### CODE REVIEW

**Comment by drewmoseley** [comment]
@leon-anavi did you verify this against all the Toradex boards?
Is there a reason you are using the 5.4.0 BSP which is no longer supported? This layer supports the [5.5 quarterly and 5.6.0 monthly releases](https://developer.toradex.com/linux-bsp/in-depth/embedded-linux-release-matrix/).

**Comment by leon-anavi** [comment]
@drewmoseley, I have verified that with the fix recipe `u-boot-distro-boot/` builds fine for machines `verdin-imx8mm` and `verdin-imx8mm`.

I have also successfully build and booted image `tdx-reference-minimal-image`  on `verdin-imx8mm`:
```
verdin-imx8mp-07154514 login: root
[  356.530664] audit: type=1006 audit(1655146686.622:2): pid=1220 uid=0 old-auid=4294967295 auid=0 tty=(none) old-ses=4294967295 ses=1 res=1
root@verdin-imx8mp-07154514:~# uname -a
Linux verdin-imx8mp-07154514 5.4.129-5.4.0-devel+git.cb88cc157bfb #1 SMP PREEMPT Wed Sep 29 18:17:21 UTC 2021 aarch64 GNU/Linux
```

For the moment I am using 5.4.0 BSP. I hope that the pull requests will be merged if there are no remarks. In the mean time I will follow-up and switch to 5.5.0 and 5.6.0.

Best regards,
Leon

**Comment by drewmoseley** [comment]
OK. As long as you were intentionally on that BSP branch then this looks good.

**Comment by drewmoseley** [comment]
@TheYoctoJester consider this my approval.

**Review by drewmoseley — APPROVED** [review]
LGTM

**Pull request merged**
