### PR TITLE
Warrior nitrogen8m

### PR DESCRIPTION
**Pull request by drewmoseley**
Some changes needed for the current warrior branch on the nitrogen8m platform.
This goes with https://github.com/boundarydevices/meta-boundary/pull/12
@texierp can you take a look?

### CODE REVIEW

**Comment by texierp** [comment]
Sure @drewmoseley ;), I will check

**Comment by drewmoseley** [comment]
I removed one patch which wasn't supposed to be here.  This is better now.

**Comment by drewmoseley** [comment]
And FWIW the required PR in meta-boundary has been merged.

**Comment by texierp** [comment]
@drewmoseley 

The build is ok on my side, but I have an issue when I want to upgrade U-Boot (`run upgradeu`). See after:

```
MMC read: dev # 0, block # 66, count 2254 ... 2254 blocks read: OK
byte at 0x000000004200208f (0xa3) != byte at 0x000000004240208f (0xad)
Total of 7311 byte(s) were the same
Need U-Boot upgrade
Program in 5 seconds
5
4
3
2
1

MMC write: dev # 0, block # 66, count 2254 ... 2254 blocks written: OK
switch to partitions #0, OK
mmc0(part 0) is current device
---- U-Boot upgraded. The board will now reset.
resetting ...

U-Boot SPL 2018.07 (Jun 29 2020 - 19:04:58 +0000)
Setting voltages
config to do 3200 1d training.
config to do 667 1d training.
config to do 3200 2d training.
Normal Boot
Trying to boot from MMC1
No matching DT out of these options:
   Configuration to load ATF before U-Boot
No matching DT out of these options:
   Configuration to load ATF before U-Boot
mmc_load_image_raw_sector: mmc block read error
SPL: failed to boot from all boot devices
### ERROR ### Please RESET the board ###
```

have you had that issue  on your side?

Here is my configuration:
```
Build Configuration:
BB_VERSION           = "1.42.0"
BUILD_SYS            = "x86_64-linux"
NATIVELSBSTRING      = "universal"
TARGET_SYS           = "aarch64-poky-linux"
MACHINE              = "nitrogen8m"
DISTRO               = "poky"
DISTRO_VERSION       = "2.7.4"
TUNE_FEATURES        = "aarch64"
TARGET_FPU           = ""
meta                 
meta-poky            
meta-yocto-bsp       = "HEAD:f65b24e9ca0918a4ede70ea48ed8b7cc4620f07f"
meta-mender-core     
meta-mender-demo     = "HEAD:5621ca878bacdf654cc63011f215192026dba7be"
meta-mender-nxp      = "warrior-nitrogen8m:498e4537002c6301ad1ca5db29eb248dad633dfd"
meta-freescale       = "HEAD:dde79e0e441cf0dae95ba42acdb9d81a384541c4"
meta-freescale-3rdparty = "HEAD:1e374913b737ae24934f799cc3592a05247a3c29"
meta-freescale-distro = "HEAD:d4e77ea682fa10d0d54a723b3d3099c44fc5e95c"
meta-oe              = "HEAD:a24acf94d48d635eca668ea34598c6e5c857e3f8"
meta-boundary        = "warrior:0beba0ebbda86342e77659ccb9efeef0094b434c"
```

Thanks !

**Comment by drewmoseley** [comment]
Hi @texierp I did not see that issue but I was not running on a stock nitrogen8m board so it's possible there is an issue with that platform.  Did you reset the environment to default after running upgradeu?

**Comment by texierp** [comment]
> Did you reset the environment to default after running upgradeu

Yes ;)

I will investigate further

**Comment by drewmoseley** [comment]
Hi @texierp any progress here?

**Comment by mirzak** [comment]
Ping @texierp @drewmoseley

**Comment by drewmoseley** [comment]
I don't have the ability to test this any more but I think it's a valid fix.  Waiting on @texierp

**Comment by texierp** [comment]
@drewmoseley @mirzak sorry for the delay, I was very busy :/ 

I will check this week ;)

**Review by texierp — APPROVED** [review]
LGTM, can you also update the revision for the meta-boundary in the README file [1] ?

https://github.com/mendersoftware/meta-mender-community/blob/warrior/meta-mender-nxp/README.md#dependencies

**Comment by texierp** [comment]
@mirzak @drewmoseley, FYI, I will update the nitrogen8m for Zeus branch.

**Comment by drewmoseley** [comment]
Readme updated.  Thanks for reviewing and testing.

**Comment by texierp** [comment]
Thanks to you @drewmoseley ;)

**Pull request merged**
