### PR TITLE
Fix build issues for Scarthgap with Jetpack 6 on Nvidia Orin Devices

### PR DESCRIPTION
**Pull request by poett1**
Quick PR to fix at least the build issues for Jetpack 6 on Orin Devices as mentioned on [Mender Hub](https://hub.mender.io/t/jetson-orin-agx-support-in-yocto-for-jetpack-6/7148). Includes Changes from [apbr/scarthgap-tegra-jetpack6](https://scarthgap-tegra-jetpack6/).
Tried this on `jetson-agx-orin-devkit-64.yml`, but it returned `L4TLauncher: Attempting Recovery Boot Failed to boot recovery:1 partition` on reboot after pushing an update, so the update process seems to require some additional changes.

### CODE REVIEW

**Comment by TheYoctoJester** [comment]
Hi @poett1,

Thanks for pulling this together. I rebased on top of current `scarthgap` and cleaned a few things out, please see https://github.com/TheYoctoJester/meta-mender-community/tree/scarthgap-tegra-jetpack6-build-fix

A test build here for the new machine configuration looks good, so I think we can move forward.

I also need Signed-Offs by both you and @apbr, for the respective commits.

**Comment by apbr** [comment]
> I also need Signed-Offs by both you and @apbr, for the respective commits.

Sure, what exactly should I do?
(I never did this before :D)

**Comment by TheYoctoJester** [comment]
> > I also need Signed-Offs by both you and @apbr, for the respective commits.
> 
> Sure, what exactly should I do? (I never did this before :D)

@apbr, I have created two branches for you:
- https://github.com/TheYoctoJester/meta-mender-community/tree/abpr_base
- https://github.com/TheYoctoJester/meta-mender-community/tree/abpr_top

Basically you need to grab the `top` branch, and do a `git commit --amend -S` on the last three commits down to the `base`. This adds a "Signed-off-by:" line to the commit message. Make sure that the given email address reflects the one which is also the git commiter. Then you push the resulting branch back up, and send me a PR against the `base`. After that I can merge and rebase the remaining.

**Comment by apbr** [comment]
Thanks, I guess you meant `git commit --amend -s` (non-capital s). I signed off my commits and send you a PR.

I guess both of you are aware that the commits are incompatible to JP5?

You also might want to pick https://github.com/apbr/meta-mender-community/commit/f5f604b57be3ea4656afa3149d959cf104c90bb8 and https://github.com/apbr/meta-mender-community/commit/3a8421ff5c02593cab59d985c30be9565638179a as well. This should probably fix the persistence of the machine-id across updates. (Or at least make it easier to finally fix it)

**Comment by TheYoctoJester** [comment]
Hi @poett1, can you sign off your three commits on https://github.com/TheYoctoJester/meta-mender-community/tree/scarthgap-tegra-jetpack6-build-fix? Then I would go ahead in picking the commits mentioned by @apbr, and hopefully merge after that.

**Comment by TheYoctoJester** [comment]
> You also might want to pick [apbr@f5f604b](https://github.com/apbr/meta-mender-community/commit/f5f604b57be3ea4656afa3149d959cf104c90bb8) and [apbr@3a8421f](https://github.com/apbr/meta-mender-community/commit/3a8421ff5c02593cab59d985c30be9565638179a) as well. This should probably fix the persistence of the machine-id across updates. (Or at least make it easier to finally fix it)

I'm just setting up a test build with those, but again, can you sign them off? ;-) @apbr

**Comment by apbr** [comment]
> > You also might want to pick [apbr@f5f604b](https://github.com/apbr/meta-mender-community/commit/f5f604b57be3ea4656afa3149d959cf104c90bb8) and [apbr@3a8421f](https://github.com/apbr/meta-mender-community/commit/3a8421ff5c02593cab59d985c30be9565638179a) as well. This should probably fix the persistence of the machine-id across updates. (Or at least make it easier to finally fix it)
> 
> I'm just setting up a test build with those, but again, can you sign them off? ;-) @apbr

Sure, forgot about it already.
They were done by @akfaro, so I guess they should sign them off?

**Comment by TheYoctoJester** [comment]
> > > You also might want to pick [apbr@f5f604b](https://github.com/apbr/meta-mender-community/commit/f5f604b57be3ea4656afa3149d959cf104c90bb8) and [apbr@3a8421f](https://github.com/apbr/meta-mender-community/commit/3a8421ff5c02593cab59d985c30be9565638179a) as well. This should probably fix the persistence of the machine-id across updates. (Or at least make it easier to finally fix it)
> > 
> > 
> > I'm just setting up a test build with those, but again, can you sign them off? ;-) @apbr
> 
> Sure, forgot about it already. They were done by @akfaro, so I guess they should sign them off?

Yeah, sign-off has to match the committer.

**Comment by akfaro** [comment]
> > > > You also might want to pick [apbr@f5f604b](https://github.com/apbr/meta-mender-community/commit/f5f604b57be3ea4656afa3149d959cf104c90bb8) and [apbr@3a8421f](https://github.com/apbr/meta-mender-community/commit/3a8421ff5c02593cab59d985c30be9565638179a) as well. This should probably fix the persistence of the machine-id across updates. (Or at least make it easier to finally fix it)
> > > 
> > > 
> > > I'm just setting up a test build with those, but again, can you sign them off? ;-) @apbr
> > 
> > 
> > Sure, forgot about it already. They were done by @akfaro, so I guess they should sign them off?
> 
> Yeah, sign-off has to match the committer.

Thanks for the hint. I have signed off  my two commits and added them to the top of @apbr's branch: 
https://github.com/apbr/meta-mender-community/commits/abpr_top/

Will you cherry-pick them yourself or do you expect a PR, @TheYoctoJester?

**Comment by poett1** [comment]
> Hi @poett1, can you sign off your three commits on https://github.com/TheYoctoJester/meta-mender-community/tree/scarthgap-tegra-jetpack6-build-fix? Then I would go ahead in picking the commits mentioned by @apbr, and hopefully merge after that.

Hello @TheYoctoJester,

I signed-off my commits and pushed them to [poett1/scarthgap-tegra-jetpack6-build-fix-poett1-sign](https://github.com/poett1/meta-mender-community/tree/scarthgap-tegra-jetpack6-build-fix-poett1-sign), hope it works like that.

**Comment by TheYoctoJester** [comment]
> > > > > You also might want to pick [apbr@f5f604b](https://github.com/apbr/meta-mender-community/commit/f5f604b57be3ea4656afa3149d959cf104c90bb8) and [apbr@3a8421f](https://github.com/apbr/meta-mender-community/commit/3a8421ff5c02593cab59d985c30be9565638179a) as well. This should probably fix the persistence of the machine-id across updates. (Or at least make it easier to finally fix it)
> > > > 
> > > > 
> > > > I'm just setting up a test build with those, but again, can you sign them off? ;-) @apbr
> > > 
> > > 
> > > Sure, forgot about it already. They were done by @akfaro, so I guess they should sign them off?
> > 
> > 
> > Yeah, sign-off has to match the committer.
> 
> Thanks for the hint. I have signed off my two commits and added them to the top of @apbr's branch: https://github.com/apbr/meta-mender-community/commits/abpr_top/
> 
> Will you cherry-pick them yourself or do you expect a PR, @TheYoctoJester?

Hi @akfaro, done, see https://github.com/mendersoftware/meta-mender-community/pull/427

**Comment by TheYoctoJester** [comment]
Hi @poett1 @apbr  @akfaro,

I have assembled all signed-off commits along with some minor clean-ups at https://github.com/mendersoftware/meta-mender-community/pull/427. Can you please review/comment/test on that one? Once we have consensus there to go ahead, I'll merge.

Thanks for your contributions!

**Pull request closed without merging**
