### PR TITLE
nxp/nitrogen8m: use a specific revision for meta-boundary

### PR DESCRIPTION
**Pull request by texierp**
Fixes:

 Trying to boot from MMC1
 No matching DT out of these options:
    Configuration to load ATF before U-Boot
 No matching DT out of these options:
    Configuration to load ATF before U-Boot
 mmc_load_image_raw_sector: mmc block read error
 SPL: failed to boot from all boot devices
 ### ERROR ### Please RESET the board ###

Signed-off-by: Pierre-Jean Texier <pjtexier@koncepto.io>

### CODE REVIEW

**Comment by mirzak** [comment]
Looks good. You know if they are planning a `thud` branch?

**Comment by texierp** [comment]
Thx @mirzak 
In fact, no response from Boundary devices (https://github.com/boundarydevices/meta-boundary/issues/5)

I will ping ;)

**Comment by mirzak** [comment]
Thanks for checking with them, merged this and hopefully they will get back to us

**Comment by texierp** [comment]
I hope too ;)
Thanks

**Pull request merged**
