### PR TITLE
PICO-IMX8M-MINI: Update patch to support DT overlay commands in pico-…

### PR DESCRIPTION
**Pull request by po-cheng-technexion**
Update in imx8mm.h
U-boot patch has to reflect the new change

Signed-off-by: Po Cheng <po.cheng@technexion.com>

### CODE REVIEW

**Comment by po-cheng-technexion** [comment]
We had sent Miraz a pico-imx8mm + pi DUT. Could you please reach out to Miraz?

**Comment by TheMeaningfulEngineer** [comment]
Hi @po-cheng-technexion 
Mirza is not available at the moment due to personal reasons.

I see that the changes you're doing are for the TechNexion board which exists only on Zeus. 
We have introduced the new program for community maintainers: https://github.com/mendersoftware/meta-mender-community/wiki/Community-maintainers

Would you like to become this for the TechNexion mender meta layer?

**Comment by richard-hu** [comment]
Hi @TheMeaningfulEngineer 

Duo to personal reason, Po can't maintain TechNexion mender meta layer anymore.
I would love to join to mender community to maintain TechNexion mender meta layer.

Thanks~

BR,

Richard

**Comment by TheMeaningfulEngineer** [comment]
Great @richard-hu thanks :)
I like to share a cup of coffee with all the maintainers to get to know them in an informal setting. 
Can you please contact me on support@mender.io so we can start looking for a timeslot?

**Comment by TheMeaningfulEngineer** [comment]
Hey @richard-hu @johnweber
shall we merge this or close the PR?

**Comment by johnweber** [comment]
I see no reason why this cannot be merged.

@richard-hu, do you agree?

**Comment by richard-hu** [comment]
Just validate the build on our build server, it competes without problem.
Please merge it and close the PR.
Thanks @johnweber  @TheMeaningfulEngineer

**Comment by TheMeaningfulEngineer** [comment]
Thanks, merging

**Pull request merged**
