### PR TITLE
mender-tezi: Add gz compression.

### PR DESCRIPTION
**Pull request by drewmoseley**
This seems to be about as fast as no compression.

Changelog: Title
Signed-off-by: Drew Moseley <drew@moseleynet.net>

### CODE REVIEW

**Comment by drewmoseley** [comment]
@ericrwx can you test this one?

**Comment by ericrwx** [comment]
@drewmoseley: Looks good. Minor issue is that `*img.bz2` files are still generated alongside the new `*.img.gz` files.

**Comment by drewmoseley** [comment]
@ericrwx I suspect you did not delete the tmp/ and deploy/ directories becore building.  I don't think it's actually generating the bz2 file; I think it was a leftover from a previous build.  Can you check?

**Comment by drewmoseley** [comment]
OK. I found where this extra file was getting added and removed it.  @ericrwx FYI

@TheYoctoJester can you give this a quick review?

**Review by TheYoctoJester — APPROVED** [review]

**Comment by drewmoseley** [comment]
Weird. @TheYoctoJester did you explicitly merge from dunfell to my branch?

**Comment by TheYoctoJester** [comment]
Yeah it said outdated branch so this was needed as preparation for merging back.

**Comment by drewmoseley** [comment]
Ahh. OK. I reused the branch name.  Thanks for taking care of this.

**Comment by TheYoctoJester** [comment]
No problem, hopefully works as expected!

**Pull request merged**
