### PR TITLE
Fix patch so that it build with the latest NXP BSP

### PR DESCRIPTION
**Pull request by gphillips-a2e**
Submitting this as requested in https://hub.mender.io/t/variscite-var-som-mx8m-nano-nxp-i-mx-8m-nano/1928/3.
I am not confident of the changes as I don't know the code, and I am experiencing problems when running the image it generates.

### CODE REVIEW

**Comment by drewmoseley** [comment]
@gphillips-a2e I see that you are explicitly adding `CONFIG_OF_LIBFDT_OVERLAY=y` and  `#define CONFIG_ENV_OVERWRITE`.  Is that intentional?

Which version of the NXP BSP are you using? Has Variscite published a matching BSP for their bits?

**Comment by gphillips-a2e** [comment]
@drewmoseley I think the adding of `CONFIG_OF_LIBFDT_OVERLAY=y` and `#define CONFIG_ENV_OVERWRITE` are likely copy and paste errors.

**Comment by gphillips-a2e** [comment]
I am using version 5.4.24-2.1.0 of meta-imx, with the zeus-imx-5.4.24-var01 branch of meta-variscite-imx.  This are the versions that were configured in Variscite's manifest, so should match.

**Comment by gphillips-a2e** [comment]
@drewmoseley 
I didn't add `CONFIG_OF_LIBFDT_OVERLAY=y` and `#define CONFIG_ENV_OVERWRITE`, they just came in as extra context lines in the patch.  It gets quite confusing trying to look at the diff of a diff.

**Comment by drewmoseley** [comment]
Yeah, no doubt. I have this building locally without needing your patch.  Can you share the list of your layers and the commit hashes of each as well as the original failure message?

**Comment by gphillips-a2e** [comment]
Here is my `conf/bblayers.conf` file:

```
LCONF_VERSION = "7"

BBPATH = "${TOPDIR}"
BSPDIR := "${@os.path.abspath(os.path.dirname(d.getVar('FILE', True)) + '/../..')}"

BBFILES ?= ""
BBLAYERS = " \
  ${BSPDIR}/sources/poky/meta \
  ${BSPDIR}/sources/poky/meta-poky \
  \
  ${BSPDIR}/sources/meta-openembedded/meta-oe \
  ${BSPDIR}/sources/meta-openembedded/meta-multimedia \
  ${BSPDIR}/sources/meta-openembedded/meta-python \
  \
  ${BSPDIR}/sources/meta-freescale \
  ${BSPDIR}/sources/meta-freescale-3rdparty \
  ${BSPDIR}/sources/meta-freescale-distro \
"

# i.MX Yocto Project Release layers
BBLAYERS += " ${BSPDIR}/sources/meta-imx/meta-bsp "
BBLAYERS += " ${BSPDIR}/sources/meta-imx/meta-sdk "
BBLAYERS += " ${BSPDIR}/sources/meta-imx/meta-ml "

BBLAYERS += "${BSPDIR}/sources/meta-browser"
BBLAYERS += "${BSPDIR}/sources/meta-rust"
BBLAYERS += "${BSPDIR}/sources/meta-openembedded/meta-gnome"
BBLAYERS += "${BSPDIR}/sources/meta-openembedded/meta-networking"
BBLAYERS += "${BSPDIR}/sources/meta-openembedded/meta-filesystems"
BBLAYERS += "${BSPDIR}/sources/meta-qt5"
BBLAYERS += "${BSPDIR}/sources/meta-python2"
BBLAYERS += "${BSPDIR}/sources/meta-swupdate"
BBLAYERS += "${BSPDIR}/sources/meta-virtualization"
BBLAYERS += "${BSPDIR}/sources/meta-variscite-imx"
#BBLAYERS += "${BSPDIR}/sources/meta-mender"

BBLAYERS += " \
  ${BSPDIR}/sources/meta-mender/meta-mender-core \
  ${BSPDIR}/sources/meta-mender/meta-mender-demo \
  ${BSPDIR}/sources/meta-mender-community/meta-mender-variscite \
"
```

**Comment by gphillips-a2e** [comment]
My hashes are:

Repo | Hash
------- | --------
base  |  01488a237cdf45b3087420e169c9f67b84fd7373
meta-browser  |  5f365ef0f842ba4651efe88787cf9c63bc8b6cb3
meta-freescale | c2a0d924f6200eea1fb1d1b61e7420ea5da2f8fb
meta-freescale-3rdparty | dbcc686f52c3c84db8cb86aa8973a4e373651b98
meta-freescale-distro  | ca27d12e4964d1336e662bcc60184bbff526c857
meta-imx   |     a083ffbbc3f4d1c02b1542746784d7f641a75b60
meta-mender   |  853b0d0a077e490de4c4706a6dcb4874183c91dc
meta-mender-community  |  0d76ca6adb8745858248531a8b8e0a0ac8197254
meta-openembedded    |   9e60d30669a2ad0598e9abf0cd15ee06b523986b
meta-python2  |  231c3d74cfcf734c3415e86ea8dd97f73ddced9d
meta-qt5   |     b8bcf8cb576d072f435a0177375e54424f67d1c9
meta-rust    |   a012a1027defe28495f06ed522a7a82bdd59a610
meta-swupdate |  8ad6a75e1778cdda671b3d6aea2a9692613020ec
meta-timesys  |  e97b31ca34018393544f82f68855bf5f82a32da4
meta-variscite-imx  |    a5a2a4c62167729d1f3d079ec199d35b21f01bd2
meta-virtualization  |   48ec1b49871fef7d331ac1d0680a48d362c7482b
poky  |  cba967414370e195d109353e51510bd829aa86c3

**Comment by gphillips-a2e** [comment]
The error message is (meta-mender-community on commit 11bab8ee3101deda7f15a92abdc8aaea85427793):

```
ERROR: u-boot-variscite-1.0-r0 do_patch: Command Error: 'quilt --quiltrc /home/yocto/nano/var-fsl-yocto/build_xwayland/tmp/work/imx8mn_var_som-poky-linux/u-boot-variscite/1.0-r0/recipe-sysroot-native/etc/quiltrc push' exited with 0  Output:
Applying patch 0001-Switch-to-CONFIG_DISTRO_DEFAULTS-for-bootcmd.patch
patching file configs/imx8mn_var_som_defconfig
Hunk #1 FAILED at 56.
1 out of 1 hunk FAILED -- rejects in file configs/imx8mn_var_som_defconfig
patching file include/configs/imx8mn_var_som.h
Hunk #1 succeeded at 60 (offset -1 lines).
Hunk #2 succeeded at 110 (offset 1 line).
Hunk #3 FAILED at 134.
Hunk #4 succeeded at 204 (offset 1 line).
Hunk #5 FAILED at 225.
Hunk #6 succeeded at 292 (offset 1 line).
2 out of 6 hunks FAILED -- rejects in file include/configs/imx8mn_var_som.h
Patch 0001-Switch-to-CONFIG_DISTRO_DEFAULTS-for-bootcmd.patch does not apply (enforce with -f)
ERROR: Logfile of failure stored in: /home/yocto/nano/var-fsl-yocto/build_xwayland/tmp/work/imx8mn_var_som-poky-linux/u-boot-variscite/1.0-r0/temp/log.do_patch.3556
ERROR: Task (/home/yocto/nano/var-fsl-yocto/sources/meta-variscite-imx/recipes-bsp/u-boot/u-boot-variscite.bb:do_patch) failed with exit code '1'
```

Here is the log file mentioned:

[log.do_patch.3556.txt](https://github.com/mendersoftware/meta-mender-community/files/5519266/log.do_patch.3556.txt)

**Comment by drewmoseley** [comment]
OK.  I do have another patch locally that I forgot about.  I have not submitted it because I have not had a chance to re-test all the builds with the new 5.4.24 BSP.  Can you test [this patch](https://github.com/drewmoseley/meta-mender-community/commit/84cbcd6fd92fb4536eb16058036e0dfe5c0a535e) locally?

**Comment by gphillips-a2e** [comment]
I replaced meta-mender-community with your fork and checked out 84cbcd6.  It is still creating the SD card image, but it looks like the patch worked and it compiled.

**Comment by drewmoseley** [comment]
OK.  Good to hear.  But I'm hesitant to move all of meta-mender-community forward as the dart-6ul still only has a 5.4.3 BSP from Variscite. For now I suggest you just keep that patch in your local checkout.

**Comment by gphillips-a2e** [comment]
@drewmoseley 
I tried the build from yesterday, it stuck in u-boot due to a problem with the environment size.  The output is below.  Do you know what the problem is?

```
U-Boot SPL 2020.04-imx_v2020.04_5.4.24_2.1.0_var01+g455f3570fb (Nov 10 2020 - 18:10:24 +0000)
Normal Boot
Trying to boot from BOOTROM
image offset 0x8000, pagesize 0x200, ivt offset 0x0


U-Boot 2020.04-imx_v2020.04_5.4.24_2.1.0_var01+g455f3570fb (Nov 10 2020 - 18:10:24 +0000)

CPU:   i.MX8MNano Quad rev1.0 1500 MHz (running at 1200 MHz)
CPU:   Commercial temperature grade (0C to 95C) at 23C
Reset cause: POR
Model: Variscite VAR-SOM-MX8MN
DRAM:  1 GiB
MMC:   FSL_SDHC: 1, FSL_SDHC: 2
Loading Environment from MMC... Run CMD11 1.8V switch
*** Error - default environment is too large

*** Error - default environment is too large

In:    serial
Out:   serial
Err:   serial

 BuildInfo:
  - ATF 0645021
  - U-Boot 2020.04-imx_v2020.04_5.4.24_2.1.0_var01+g455f3570fb


Part number: VSM-MX8MN-101
Assembly: AS2006152614
Production date: 2020 Jul 02
Serial Number: f8:dc:7a:46:04:5e
env_buf [32 bytes] too small for value of "bootcmd"
Net:
Warning: ethernet@30be0000 (eth0) using random MAC address - 26:8f:1b:6f:f8:5d
eth0: ethernet@30be0000
Fastboot: Normal
Normal Boot
env_buf [32 bytes] too small for value of "bootcmd"
Hit any key to stop autoboot:  0
syntax error
Unknown command '@' - try 'help'
u-boot=>
```

**Comment by gphillips-a2e** [comment]
It looks like the only difference between the patch in this pull request and the one in 84cbcd6 is that the one in the pull request keeps the addition of `#define CONFIG_ENV_SIZE    SZ_8K`.  The u-boot error message seems to imply this is required.

**Comment by drewmoseley** [comment]
Yes, due to the changes made in the patch, we need more env space.

**Comment by gphillips-a2e** [comment]
I tried 84cbcd6 with the environment size increased to 8K.  This boots but has the same issues as my original attempt (slow boot, `memcg_kmem_cache_create_func` messages, does not start GUI, cannot log in).

Do you have any other suggestions?

**Comment by drewmoseley** [comment]
No clue.  Does "systemd-analyze blame" show anything of note?

**Comment by gphillips-a2e** [comment]
I am not able to get to the point where I can run any commands.  I can get as far as entering an user name and then it gets stuck and periodically prints large blocks of `memcg_kmem_cache_create_func`.

**Comment by drewmoseley** [comment]
Which DISTRO are you building with? I'll try to replicate here.

**Comment by gphillips-a2e** [comment]
I am building Zeus 5.4.24 on Ubuntu 18.04.  The manifest is imx-5.4.24-2.1.0-var01.xml.

**Comment by gphillips-a2e** [comment]
I tried this on a VAR-SOM-MX8M-MINI board with the imx-5.4.3-1.0.1-var01.xml manifest.  The result is the similar.  It needs `MENDER_STORAGE_TOTAL_SIZE_MB` increasing to create the image, it starts up to the command line instead of the GUI, and logging in via the console does not work.  The only difference is that I cannot see the `memcg_kmem_cache_create_func` message.

**Comment by drewmoseley** [comment]
@gphillips-a2e please take a look at https://github.com/mendersoftware/meta-mender-community/pull/191.
That works for me on the core-image* builds.  If you can test the fsl-image* builds that would be helpful.  I'll close this in favor of that one.

**Comment by gphillips-a2e** [comment]
@drewmoseley 
The fsl-image-qt5 image does not work for me.  I get the same problems as I described previously.  I have not tried any other fsl-image builds.   Although core-image-full-command line worked for me core-image-weston did not.  The weston image had similar issues to fsl-image-qt5.

**Pull request closed without merging**
