### PR TITLE
Add support for Beaglebone Black

### PR DESCRIPTION
**Pull request by drewmoseley**
Signed-off-by: Drew Moseley <drew.moseley@northern.tech>

### CODE REVIEW

**Comment by drewmoseley** [comment]
@mirzak for some reason I cannot assign or request reviews on this repo.

**Comment by mirzak** [comment]
Odd, you have admin rights on this repository. I noticed that I had not added a "team", I have now and let me know if this changed anything.

**Comment by mirzak** [comment]
Should we enable U-boot integration on BBB on `thud`, because it will default to the U-boot -> GRUB here.

**Comment by drewmoseley** [comment]
> Odd, you have admin rights on this repository. I noticed that I had not added a "team", I have now and let me know if this changed anything.

Yes, I know have the proper permissions.

> Should we enable U-boot integration on BBB on thud, because it will default to the U-boot -> GRUB here.

I don't think that's necessary.  I just added this here in case users want to enable it themselves.

**Comment by mirzak** [comment]
Ok, merging as is. Thanks

**Pull request merged**
