### PR TITLE
Fixed Toradex imx8 patches not applying

### PR DESCRIPTION
**Pull request by Lachlan-Frawley**
Toradex made some changes in their latest Kirkstone BSP layers which stops the Mender integration patches from being applied.

I manually re-applied the patches and wrote back the correct changes to the original patch files.

### CODE REVIEW

**Comment by TheYoctoJester** [comment]
Can you comment @drewmoseley / @leon-anavi ?

**Comment by leon-anavi** [comment]
Hi @Lachlan-Frawley, @TheYoctoJester,

As far as I can see these changes affect only Toradex Apalis i.MX8 and Toradex BSP 6.0.0, right? If so probably the git commit message should note it. Also the change in **u-boot-toradex_%.bbappend** is kind of redundant because it just removes a new line.

Although Toradex BSP 6.0.0 is based on Kirkstone it is not the latest release because [6.1.0 was released on January 23, 2023](https://www.toradex.com/news/bsp-layers-reference-images-yocto-project-6-1-0-quarterly).

I am a bit confused because according to the BSP changelogs Toradex states for [6.0.0](https://www.toradex.com/news/bsp-layers-reference-images-yocto-project-6-0-0-quarterly): 
> Support for Apalis iMX8 and Colibri iMX8X is planned in the next releases

and for [6.1.0](https://www.toradex.com/news/bsp-layers-reference-images-yocto-project-6-1-0-quarterly):

> [Apalis iMX8](https://www.toradex.com/computer-on-modules/apalis-arm-family/nxp-imx-8) Support was added in the downstream-based BSP

Regarding these circumstances why do we need rebasing patches for Apalis iMX8 in BSP 6.0.0?

I tried building  **tdx-reference-minimal-image** following the [tutorial in Mender Hub for Apalis iMX8](https://hub.mender.io/t/toradex-apalis-i-mx8/4103/1) with BSP 6.0.0 and linux-toradex failed because of missing device tree target 'arch/arm64/boot/dts/freescale/imx8qm-apalis-v1.1-ixora-v1.2.dtb'. I haven't looked in details but this was kind of expected considering the description of the BSPs from Toradex.

I don't have Apalis iMX8 around here so I can do full testing but I guess it will be better to migrate meta-mender-community to Toradex BSP 6.1.0 and after that fix patches accordingly.

Best regards,
Leon

**Comment by Lachlan-Frawley** [comment]
Sorry, I suppose I should be more specific. I pulled the latest Toradex Kirkstone layers and found that they had changed the defconfig for the apalis-imx8 in u-boot-toradex, seen here: https://git.toradex.com/cgit/u-boot-toradex.git/commit/?h=toradex_imx_lf_v2022.04&id=b1103fcd165570265cab0145a60707cd168e9fab

This caused the patches to not apply for Mender integration.

**Comment by drewmoseley** [comment]
Hi guys. My apologies for the delayed response. I've been traveling for Embedded World and my focus has been elsewhere.

I agree with @leon-anavi that we should wait for official apalis-imx8 support in the Toradex BSP. It's due pretty soon so rather than spending time now only to potentially have to change it if there are any late-breaking changes from the BSP team, I think we are better just waiting a bit.  If you need this working now you can use the changes here locally.

I'll check with the team and see if there is any update to the actual BSP 6.x release for this platform and we can then decide how best to proceed.

**Comment by Lachlan-Frawley** [comment]
Sure, that sounds pretty reasonable. Thanks for all the input.

**Pull request closed without merging**
