### PR TITLE
Add missing repo sync step to README.md

### PR DESCRIPTION
**Pull request by dwalkes**
Per discussion in #15

### CODE REVIEW

**Comment by mirzak** [comment]
Thanks, merged. Up for creating a "cherry-pick" to "rocko" branch as well?

**Comment by dwalkes** [comment]
> Up for creating a "cherry-pick" to "rocko" branch as well?
Sure thing, see #17

**Comment by dwalkes** [comment]
Also added one for morty in #18

**Comment by mirzak** [comment]
Thanks!

**Pull request merged**
