### PR TITLE
Add Raspberry Pi 5 Support in meta-mender-community/meta-mender-raspberrypi

### PR DESCRIPTION
**Pull request by leon-anavi**
Hi,

This GitHub pull request contains patches to enable Mender on Raspberry Pi 5 using meta-raspberrypi and meta-lts-mixins (for U-Boot 2024.04). It has been tested on Raspberry Pi 4 and Raspberry Pi 5 with the following configurations:

* machine `raspberrypi5` with U-Boot 2024.04 with meta-lts-mixins
* machine `raspberrypi4-64` with U-Boot 2024.04 with meta-lts-mixins
* machine `raspberrypi4-64` with U-Boot 2024.01

This GitHub pull request depends on:
* Support Scarthgap in meta-mender https://github.com/mendersoftware/meta-mender/pull/2103
* Consolidated preparation and bump to scarthgap #379

Once GitHub pull request #379 gets merged, I will rebase this GitHub PR on top of it. I am opening it right now to get early feedback about the Raspberry Pi 5 work.

Best regards, Leon

### CODE REVIEW

**Comment by TheYoctoJester** [comment]
Hi @leon-anavi, I have created the `scarthgap` branch. Can you rebase to it? Plus two additional remarks:
- at least for now, the layer directory should be called `meta-mender-raspberrypi-community`
- can you also add a kas file? This makes the `meta-lts-mixins´ dependency clear and easily reproducible.

**Comment by leon-anavi** [comment]
Hi @TheYoctoJester,

> Hi @leon-anavi, I have created the `scarthgap` branch. Can you rebase to it? Plus two additional remarks:

Yes, done

> * at least for now, the layer directory should be called `meta-mender-raspberrypi-community`

OK, as part  of the rebase I created sub-layer `meta-mender-raspberrypi-community`.

> * can you also add a kas file? This makes the `meta-lts-mixins´ dependency clear and easily reproducible.

Here I have a problem with the mender integration when I try to use branch `scarthgap` of your https://github.com/TheYoctoJester/meta-mender, aka https://github.com/mendersoftware/meta-mender/pull/2099:

```
root@raspberrypi5:~# mender
-sh: mender: command not found
```
In my `local.conf` I have:

```
# mender-full
INHERIT += "mender-full"
```

Is there anything special from https://github.com/TheYoctoJester/meta-mender branch `scarthgap`  that I am missing?

It works fine if I switch meta-mender to my GitHub pull request for scarthgap in meta-mender: https://github.com/mendersoftware/meta-mender/pull/2103

Here are more details about the layers in my setup:
* **OK** with https://github.com/mendersoftware/meta-mender/pull/2103:
```
meta                 
meta-poky            
meta-yocto-bsp       = "scarthgap:fb91a49387cfb0c8d48303bb3354325ba2a05587"
meta-oe              = "scarthgap:6819f825caf750b4deac5d8dda1b81f3380615be"
meta-raspberrypi     = "master:1879cb831f4ea3e532cb5ce9fa0f32be917e8fa3"
meta-mender-core     
meta-mender-raspberrypi = "scarthgap-rpi5-support:541a14e304bad1066541303caf95fc71d6236cd3"
meta-mender-raspberrypi-community = "rpi5-master:dbd528b3b5b9124df551d237f49b40e06256ca45"
meta-lts-mixins      = "scarthgap/u-boot:66ceeebd047d7fdfc8668b300319a76da8ae257d"
```

* **FAIL** with https://github.com/mendersoftware/meta-mender/pull/2099:

```
meta                 
meta-poky            
meta-yocto-bsp       = "scarthgap:fb91a49387cfb0c8d48303bb3354325ba2a05587"
meta-oe              = "scarthgap:6819f825caf750b4deac5d8dda1b81f3380615be"
meta-raspberrypi     = "master:1879cb831f4ea3e532cb5ce9fa0f32be917e8fa3"
meta-mender-core     
meta-mender-raspberrypi = "scarthgap:1e727c2a72bc6713a013855166eab9625b4817a7"
meta-mender-raspberrypi-community = "rpi5-master:dbd528b3b5b9124df551d237f49b40e06256ca45"
meta-lts-mixins      = "scarthgap/u-boot:66ceeebd047d7fdfc8668b300319a76da8ae257d"
```

Best regards, Leon

**Comment by TheYoctoJester** [comment]
Hi @leon-anavi, that's probably because of the migration to Mender Client 4.0. The `mender` binary has been split into `mender-auth` and `mender-update`, so you have to check using the latter one. I have assembled the necessary information here: https://hub.mender.io/t/using-mender-client-4-0-on-yocto/6767

**Comment by TheYoctoJester** [comment]
Hi @leon-anavi, tried to build this branch now for testing, and `u-boot` is being skipped:
`ERROR: Nothing PROVIDES 'u-boot'
u-boot was skipped: Either UBOOT_MACHINE or UBOOT_CONFIG must be set in the raspberrypi5 machine configuration.
u-boot was skipped: incompatible with machine raspberrypi5 (not in COMPATIBLE_MACHINE)
ERROR: Required build target 'core-image-minimal' has no buildable providers.
Missing or unbuildable dependency chain was: ['core-image-minimal', 'u-boot']`
As far as I can tell the layer revisions match, anything else you have in your setup?

**Comment by leon-anavi** [comment]
> As far as I can tell the layer revisions match, anything else you have in your setup?

This GitHub pull request contains `u-boot_2024.04.bbappend` that marks Raspberry Pi 5 as a compatible machine for U-Boot: https://github.com/mendersoftware/meta-mender-community/pull/380/commits/dbd528b3b5b9124df551d237f49b40e06256ca45#diff-550da7d60d61f8bf246c3ace54ca982ab13f37a9df8435f0c46f637d92ea9a02R1 Do you have this in your setup?

Best regards,
Leon

**Comment by leon-anavi** [comment]
@TheYoctoJester I see recipes and patches coming with meta-mender-raspberrypi have been removed from the GitHub PR for meta-mender: https://github.com/TheYoctoJester/meta-mender/commit/9428935c278f88e3bede57fd1edcf9a8f5f991f6 What is the plan regarding these bits? Should I add them to meta-mender-raspberrypi-community as part of this GitHub pull request?

Thanks,
Leon

P.S. after some debugging on Raspberry Pi 5, it seems that we need to move recipes, bbappend files and patches from the removed sub-layer meta-mender-raspberrypi (from meta-mender) to meta-mender-community and meta-mender-raspberrypi-community. We also need to replace `mender-client-install` with `mender-update-install`. [I did these changes in commit a5ff16b34e25722ec967fdff1beb0e227c643a16](https://github.com/leon-anavi/meta-mender-community/commit/a5ff16b34e25722ec967fdff1beb0e227c643a16). Depending on the plan if you want I can include this commit as part of this GitHub pull request.

**Comment by TheYoctoJester** [comment]
@leon-anavi yeah, sorry for the bad timing. The move of `meta-mender-raspberrypi` into `meta-mender-community` was discussed and decided after we had already started on the 'meta-mender-raspberrypi-community` effort.
So in summary, we will combine it :-) Its just a bit too many moving parts right now as `scarthgap` on `meta-mender` also needs sorting out.
I'll keep you updated!

**Comment by leon-anavi** [comment]
> @leon-anavi yeah, sorry for the bad timing. The move of `meta-mender-raspberrypi` into `meta-mender-community` was discussed and decided after we had already started on the 'meta-mender-raspberrypi-community`effort. So in summary, we will combine it :-) Its just a bit too many moving parts right now as`scarthgap`on`meta-mender` also needs sorting out. I'll keep you updated!

OK, I rebased the patches. Now this GitHub pull request adds all required configurations in sub-layer `meta-mender-raspberrypi-community`, including kas configuration files for Raspberry Pi 5 which can be built with:

```
kas build meta-mender-community/kas/raspberrypi5.yml
```

I successfully tested a mender update manually by installing it with the following sequence:

* Download and install the update:
```
mender-update install http://192.168.1.101:8000/core-image-minimal-raspberrypi5.mender
```
* Reboot Raspberry Pi 5:
```
reboot
```
* Verify the update is successful and commit it:
```
mender-update commit
```

Temporary the kas configurations use repositories containing GitHub pull requests for adding support for Yocto release scarthgap in Mender, aka the one for this GitHub PR and https://github.com/mendersoftware/meta-mender/pull/2099

@TheYoctoJester could you please review the modified version of the GitHub pull request and the kas configurations?

Best regards, Leon

**Comment by TheYoctoJester** [comment]
Hi @leon-anavi, looks nice, also passed my test build pipeline. The only remaining concern I have at the moment is the scope of `meta-lts-mixins`, see also https://hub.mender.io/t/raspberry-pi-latest-u-boot-or-yocto-lts-one/6793. I'm not sure what the best and most robust way forwards for users is.
Oh, and as the `meta-mender-raspberrypi` layer has now been folded into it, we can remove the `-community` tail in this name. Want me to do it?

**Comment by TheYoctoJester** [comment]
Hi @leon-anavi, I've pushed the last things I had in my pipeline to your branch. Can you give it a short review? If you're fine with it, I'll merge. 🎉

**Review by TheYoctoJester — APPROVED** [review]

**Comment by leon-anavi** [comment]
Hi @TheYoctoJester,

> Hi @leon-anavi, I've pushed the last things I had in my pipeline to your branch. Can you give it a short review? If you're fine with it, I'll merge. 🎉

Thank you for your improvements. I had a look at the changes and they all look good to me.

Thanks, Leon

**Pull request merged**
