### PR TITLE
Wip morty

### PR DESCRIPTION
**Pull request by drewmoseley**
Add the first platform supported in the morty branch.

Note that this is a bit convoluted due to wanting to stay with the Compulab provided BSP.

### CODE REVIEW

**Comment by drewmoseley** [comment]
@mirzak please take a look.  This implements the Compulab builds by starting with the Compulab BSP and adding the Mender bits through local_manifests.

**Comment by mirzak** [comment]
I looks great @drewmoseley.

I would squash:

```
compulab: New community layer.  …
u-boot: Add support for cl-som-imx6 U-Boot and friends.  …
Initial template files for compulab builds  …
Clean up compulab readme to use the Compulab and FSL BSPs.  …
```

**Comment by drewmoseley** [comment]
@mirzak squashed as requested.  Otherwise this is identical

**Comment by mirzak** [comment]
Thanks, merging.

**Pull request merged**
