### PR TITLE
Update README.md of meta-mender-toradex-nxp

### PR DESCRIPTION
**Pull request by mattes-bru**
Enhanced and updated QuickStart

### CODE REVIEW

**Comment by drewmoseley** [comment]
@TheYoctoJester ping

**Comment by TheYoctoJester** [comment]
Thanks Drew I just need an SOB 👍

Drew Moseley ***@***.***> schrieb am Do. 15. Juni 2023 um
18:22:

**Comment by drewmoseley** [comment]
@mattes-bru the above comment is for you. A "signed-off-by" tag is needed in your commit message: https://github.com/mendersoftware/mender/blob/master/CONTRIBUTING.md#providing-pull-requests

**Comment by mattes-bru** [comment]
@drewmoseley thanks for the hint

@TheYoctoJester SOB is added

**Comment by fboudra** [comment]
sorry, I've just sent a PR before noticing this one.

@TheYoctoJester can you merge this one and close mine? thanks!

**Review by TheYoctoJester — APPROVED** [review]

**Comment by TheYoctoJester** [comment]
@fboudra done, thanks for the ping.

**Pull request merged**
