### PR TITLE
layer: update email address for Pierre-Jean Texier

### PR DESCRIPTION
**Pull request by texierp**
Signed-off-by: Pierre-Jean Texier <texier.pj2@gmail.com>

### CODE REVIEW

**Comment by TheMeaningfulEngineer** [comment]
Hi @texierp ,
we have started to track Community maintainer in a single place.
You can see what being a community maintainer means here: 
https://github.com/mendersoftware/meta-mender-community/wiki/Community-maintainers

Would you be ok that we add the email `texier.pj2@gmail.com` as the maintainer for `meta-mender-atmel`?

**Comment by texierp** [comment]
Hi @TheMeaningfulEngineer ,

> Hi @texierp ,
> we have started to track Community maintainer in a single place.
> You can see what being a community maintainer means here:
> https://github.com/mendersoftware/meta-mender-community/wiki/Community-maintainers

Oh nice ;) , thanks for the feedback.

> 
> Would you be ok that we add the email `texier.pj2@gmail.com` as the maintainer for `meta-mender-atmel`?

Yes, fine for me, should I send a PR ?

**Comment by TheMeaningfulEngineer** [comment]
@texierp 
> Yes, fine for me, should I send a PR ?

No need, thanks. I'm owning keeping track of the maintainers, and have updated you in the table.

**Comment by TheMeaningfulEngineer** [comment]
Merging this now.

**Comment by TheMeaningfulEngineer** [comment]
@texierp 
I've missed this. 
Would you like to be the maintainer for meta-mender-nxp also?
 
Just noticed the other file in the PR.

**Comment by texierp** [comment]
> @texierp
> I've missed this.
> Would you like to be the maintainer for meta-mender-nxp also?

Yes, no problem for me :)

**Pull request merged**
