### PR TITLE
pico-pi-imx7d: bump to dunfell

### PR DESCRIPTION
**Pull request by texierp**

### CODE REVIEW

**Comment by texierp** [comment]
depends on https://github.com/mendersoftware/meta-mender/pull/1398

**Comment by TheMeaningfulEngineer** [comment]
Hey @texierp 
there is a PR for backporting the patch to meta-mender.
https://github.com/mendersoftware/meta-mender/pull/1401

Once it's done I will merge this.

**Comment by texierp** [comment]
Thanks for the feedback @TheMeaningfulEngineer ;)

**Comment by texierp** [comment]
Hi @TheMeaningfulEngineer 

This PR can be merged ;)
Commit in meta-mender is now on dunfell [1]

[1] - https://github.com/mendersoftware/meta-mender/commit/906c17722eace50674f3b9983c1f5d2f989ab699

**Comment by TheMeaningfulEngineer** [comment]
Thanks @texierp
Merging

**Pull request merged**
