### PR TITLE
Rockchip kirkstone updates

### PR DESCRIPTION
**Pull request by nandra**

### CODE REVIEW

**Comment by TheYoctoJester** [comment]
Hi @nandra,

thanks for the submission, its already merged. However I have some problems in actually verifying the build. This is, as far as I can see, due to two main things:
- the repo xml not being updated since `thud`, which means I don't have an automated way to set up a build
- the Readme not saying anything about the supported/targetted board nor dependencies.
If you could provide some more information, also in free form here, then I'd try to replicate the build and document it accordingly.

Thanks,
Josef

**Comment by nandra** [comment]
Hi @TheYoctoJester , ok I'll psuh few more updates as I was testing it with kas and not with repo infrastructure as in this repo ;). Sorry and thanks.

**Comment by TheYoctoJester** [comment]
No problem @nandra, if you drop me a (sanitized) kas file, that also works for me to extract the data. I'm moving to that anyways, you can see the current state of things [here](https://github.com/TheYoctoJester/meta-mender-community/tree/kas-kirkstone) and [here](https://github.com/TheYoctoJester/meta-mender-community/tree/kas-dunfell).

**Comment by nandra** [comment]
@TheYoctoJester here is snippet for kas config file:
```local_conf_header:
   mender: |
     MENDER_ARTIFACT_NAME ?= "release-1"
     MENDER_FEATURES_ENABLE:append = " mender-uboot mender-image mender-client-install mender-image-sd"
     MENDER_FEATURES_DISABLE:append = " mender-grub mender-image-uefi"


     MENDER_UBOOT_STORAGE_INTERFACE = "mmc"
     MENDER_UBOOT_STORAGE_DEVICE = "1"
     IMAGE_CLASSES += "rockchip-sdimg"
     # install only boot.scr. We don't need boot.img in boot partition
     # simply IMAGE_BOOT_FILE = "boot.src doesn't work so first remove, then append"
     IMAGE_BOOT_FILES:remove = "fitImage"
     IMAGE_BOOT_FILES:append = "boot.scr"

     IMAGE_FSTYPES:remove = "wic wic.bmap mender.bmap"
     # we need to move env to offset 10M as it clash with u-boot
     MENDER_PARTITION_ALIGNMENT = "10485760"
```

and I've tested it on rock-pi-e rk3328 board (I'll add documentation to hub soon). I don't have Firefly unfortunately so cannot verify. Thanks.

**Comment by TheYoctoJester** [comment]
Hi @nandra,

Perfect! I’ll spin up the test builds this afternoon. I take it no special
layers other than meta-rockchip are needed? Which machines are expected to
be good?

Greets

Marek Belisko ***@***.***> schrieb am Mi. 19. Apr. 2023 um
07:25:

**Comment by nandra** [comment]
Hi @TheYoctoJester , only meta-rockchip is necessary. `rock-pi-e` should build just fine ;) as I've used this one for development.

**Pull request merged**
