### PR TITLE
Toradex bsp6 kirkstone

### PR DESCRIPTION
**Pull request by drewmoseley**
This patch set gets rid of all old BSP5 settings and gets the following boards working with Toradex BSP6:
* apalis-imx6
* colibri-im6ull
* verdin-imx8mm
* verdin-imx8mp

Notably, the following boards are not supported yet by Toradex BSP6 even though some of the patches in this set have been build-tested:
* apalis-imx8
* colibri-imx8x

### CODE REVIEW

**Comment by drewmoseley** [comment]
This is dependent on https://github.com/mendersoftware/meta-mender/pull/1849

**Review by TheYoctoJester — APPROVED** [review]
Looks good to me. Shall we wait for @leon-anavi to review or merge?

**Review by leon-anavi — APPROVED** [review]
Looks good to me. I will test in the coming days/weeks for verdin imx8mp but you can merged it right now.

Thanks, Leon

**Comment by leon-anavi** [comment]
I am doing some testing and there are a couple of issues:

* We need to add a bigger `MENDER_STORAGE_TOTAL_SIZE_MB` for verdin-imx8mp, aka in `meta-mender-toradex-nxp/templates/local.conf.append`

```
MENDER_STORAGE_TOTAL_SIZE_MB:verdin-imx8mp = "2048"
```

* Mender install fails:

```
INFO[0000] Loaded configuration file: /var/lib/mender/mender.conf 
INFO[0000] Loaded configuration file: /etc/mender/mender.conf 
INFO[0000] Output (stderr) from command "grub-mender-grubenv-print": Cannot determine environment directory. 
INFO[0000] Output (stderr) from command "grub-mender-grubenv-print": Cannot determine environment directory. 
ERRO[0000] Failed to read the current active partition: No match between boot and root partitions.: exit status 2 
```

Best regards,
Leon

**Comment by drewmoseley** [comment]
@leon-anavi thanks for testing. I rebased and added a commit to increase TOTAL_STORAGE_SIZE_MB for verdin-imx8mp.

@TheYoctoJester from my POV this is good to go.

**Pull request merged**
