### PR TITLE
Add the readme structure for maintainers

### PR DESCRIPTION
**Pull request by TheMeaningfulEngineer**

### CODE REVIEW

**Comment by TheMeaningfulEngineer** [comment]
@kacf 
Something like this.

(I'm having issues with the signature `git commit -S` is not letting go of attempts to sign with gpg.
Will get back to see how to fix it.)

**Review by kacf — APPROVED** [review]
Great!

Note that it's lowercase `-s` to sign off, it's unrelated to gpg signing.

**Comment by TheMeaningfulEngineer** [comment]
> Note that it's lowercase -s to sign off, it's unrelated to gpg signing.

Thanks. 
The price I pay for trying to ramp up thing with half of my brain. :)

**Comment by lluiscampos** [comment]
:+1:

**Pull request merged**
