### PR TITLE
RFC toradex: Move dtb and dtbo files to root partition.

### PR DESCRIPTION
**Pull request by drewmoseley**
These files should be loaded from the rootfs partition so we can update them OTA.

Changelog: Title
Signed-off-by: Drew Moseley <drew@moseleynet.net>

### CODE REVIEW

**Comment by drewmoseley** [comment]
@TheYoctoJester @leon-anavi I would love your input on this. I noticed that we were not pulling DTB and DTBO files from the rootfs partition so there was no way to update them OTA.  This patch adds that capability. This was discovered while trying to do an OTA from dunfell to kirkstone and is required for that ability. I have an equivalent patch on kirkstone that I am working on but getting it into dunfell is a necessary first step.

**Comment by TheYoctoJester** [comment]
@drewmoseley yeah we've run into a similar situation. I personally think that this looks good and is the correct approach. From a version management perspective, `kirkstone` is meant to take the lead now on this repo.

**Comment by drewmoseley** [comment]
About using kirkstone, understood but this is required if we want to allow OTA between dunfell and kirkstone so I figured we start here. I have the equivalent fix for kirkstone in my WIP branch locally and will submit that once we make a final decision on this one.

**Comment by drewmoseley** [comment]
Let's wait for @leon-anavi; he's the only other active user that I am aware of.

**Comment by leon-anavi** [comment]
Sounds as a very good idea and the patch looks good to me. 

Thanks, Leon

**Comment by drewmoseley** [comment]
OK.  In that case I guess we are good to go.

**Review by TheYoctoJester — APPROVED** [review]

**Pull request merged**
