### PR TITLE
Dunfell

### PR DESCRIPTION
**Pull request by drewmoseley**
This contains the update from here: https://github.com/mendersoftware/meta-mender-community/pull/244
But also a few other bug fixes.

### CODE REVIEW

**Comment by TheMeaningfulEngineer** [comment]
Thanks @drewmoseley 
Your call when you want to merge this.

**Comment by drewmoseley** [comment]
Yeah, thanks. I'm waiting for @pgiangrossi to review and let me know if this fixes the issues [he reported here](https://hub.mender.io/t/no-video-on-toradex-apalis-imx8/4051/17).

**Review by kacf — APPROVED** [review]
The boot code is hard to comment on without knowing the board, but looks good from a generic standpoint.

**Comment by pgiangrossi** [comment]
The overlay apply is verified to work on Apalis IMX8 with LVDS display, although there is one error message observed during execution of the boot.scr script shown below ("Unknown command '0x9c000000'):

`Found U-Boot script /boot.scr
2691 bytes read in 19 ms (137.7 KiB/s)
## Executing script at 83100000
Unknown command '0x9c000000' - try 'help'
Loading hdp firmware from 0x000000009c000000 offset 0x0000000000002000
Loading hdp firmware Complete
Saving Environment to MMC... Writing to redundant MMC(0)... OK
Loading DeviceTree: imx8qm-apalis-v1.1-eval.dtb
166596 bytes read in 22 ms (7.2 MiB/s)
108 bytes read in 10 ms (9.8 KiB/s)
Applying Overlay: apalis-imx8_lvds_overlay.dtbo
638 bytes read in 21 ms (29.3 KiB/s)
Applying Overlay: apalis-imx8_atmel-mxt_overlay.dtbo
402 bytes read in 19 ms (20.5 KiB/s)
Applying Overlay: display-lt170410_overlay.dtbo
834 bytes read in 21 ms (38.1 KiB/s)
10260548 bytes read in 248 ms (39.5 MiB/s)
Uncompressed size: 24267264 = 0x1724A00
Bootargs: pci=nomsi root=/dev/mmcblk0p2 ro rootwait
## Flattened Device Tree blob at 83000000
   Booting using the fdt blob at 0x83000000
   Loading Device Tree to 00000000fcdff000, end 00000000fce4afff ... OK

Starting kernel ...`

**Comment by drewmoseley** [comment]
@pgiangrossi that's interesting since the immediate next command uses `0x000000009c000000` as an address.  Can you confirm you did not see this before when using the overlays?

**Comment by pgiangrossi** [comment]
I do not see that error when I run my own patch.

**Comment by pgiangrossi** [comment]
The error is happening at the "run setup" command.  
`setup=run loadhdp; hdp load ${hdp_addr}; run mmcargs
loadhdp=${load_cmd} ${hdp_addr} {hdp_file}`

load_cmd is undefined at this point. In my patch, I moved this definition before the "run setup" command.

**Comment by drewmoseley** [comment]
@pgiangrossi thanks. I just figured that out myself and pushed a fix. Can you retest?

**Comment by pgiangrossi** [comment]
Re-tested with latest fix. Display works fine, mender update works fine. No errors observed in U-boot.

Looks good to me.

**Comment by drewmoseley** [comment]
Thank for the help. Merging.

**Pull request merged**
