### PR TITLE
sunxi - thud update

### PR DESCRIPTION
**Pull request by nandra**
Tested on orangepi zero

### CODE REVIEW

**Comment by mirzak** [comment]
Could you rebase this on latest "thud" revision. Tried testing it out but you are missing updates to the `mender.xml` file

**Comment by nandra** [comment]
Force pushed

**Comment by mirzak** [comment]
Hmm. Did you do a git merge? Because this PR now has 13 commits

**Comment by nandra** [comment]
Yes because base is sumo not thud. Let me close this one and open new one

**Comment by nandra** [comment]
#35 updated

**Pull request closed without merging**
