### PR TITLE
Validate Variscite var-som-mx6 on sumo

### PR DESCRIPTION
**Pull request by drewmoseley**
Signed-off-by: Drew Moseley <drew.moseley@northern.tech>

### CODE REVIEW

**Comment by drewmoseley** [comment]
For ease of review, the diff between meta-mender-variscite here and in my rocko version (https://github.com/mendersoftware/meta-mender-community/pull/55) is almost nothing:

```
$ git diff drewmoseley/rocko meta-mender-variscite/
diff --git a/meta-mender-variscite/conf/layer.conf b/meta-mender-variscite/conf/layer.conf
index 2524da5..d9c1e5d 100644
--- a/meta-mender-variscite/conf/layer.conf
+++ b/meta-mender-variscite/conf/layer.conf
@@ -10,3 +10,5 @@ BBFILE_PATTERN_mender-variscite = "^${LAYERDIR}/"
 BBFILE_PRIORITY_mender-variscite = "10"

 LAYERDEPENDS_mender-variscite = "mender variscite-imx"
+
+LAYERSERIES_COMPAT_mender-variscite = "sumo"
diff --git a/meta-mender-variscite/recipes-bsp/u-boot/u-boot-variscite-mender-common.inc b/meta-mender-variscite/recipes-bsp/u-boot/u-boot-variscite-mender-common.inc                                
index 2b7ff40..ce6c95a 100644
--- a/meta-mender-variscite/recipes-bsp/u-boot/u-boot-variscite-mender-common.inc
+++ b/meta-mender-variscite/recipes-bsp/u-boot/u-boot-variscite-mender-common.inc
@@ -6,6 +6,7 @@ FILESEXTRAPATHS_prepend := "${THISDIR}/patches:"

 SRC_URI_append_imx6ul-var-dart = " file://0001-mx6ul_var_dart-Remove-unneeded-boot-settings.patch "                                                                                                  
 SRC_URI_append_var-som-mx6 = " file://0001-mx6var_som-Remove-unneeded-boot-settings.patch "
+SRC_URI_remove_var-som-mx6 = " file://0006-env-Kconfig-Add-descriptions-so-environment-options-.patch"                                                                                               

 MENDER_UBOOT_PRE_SETUP_COMMANDS_var-som-mx6 = " \
     setenv bootargs console=\${console},\${baudrate}; \
```

**Comment by drewmoseley** [comment]
@mirzak this one is ready to go now.

**Comment by mirzak** [comment]
Nice

**Comment by mirzak** [comment]
Need a Mender Hub post for `var-dart` as well

**Pull request merged**
